version: "3.7"

services:
  database:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: P123456p
      MYSQL_USER: clarusway
      MYSQL_PASSWORD: Clarusway_1
      MYSQL_DATABASE: bookstore_db
    networks:
      - clarusnet

  myapp:
    image: hamidgokce/bookstoreapi:latest
    container_name: myapp
    restart: always
    depends_on: # The database must be created first.
      - database
    ports:
      - "80:80"
    networks:
      - clarusnet

networks:
  clarusnet: # default driver is bridge
    driver: bridge


